
ARG PYTHON_VERSION=3.11.2
FROM python:${PYTHON_VERSION}-slim as base


RUN apt-get update && apt-get install -y libpq-dev postgresql-client

RUN pip install fastapi uvicorn sqlalchemy psycopg2-binary


COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app

EXPOSE 8000


ENV NAME World


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]