version: '3'
services:
  db:
    container_name: mydbcontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  web:
    container_name: mywebcontainer
    build:
      context: .
      dockerfile: Dockerfile.web  
    ports:
      - "8000:8000"
    depends_on:
      - db